import { Book } from './types.ts';

export const BOOKS: Book[] = [
  {
    id: '1',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    price: 1499,
    rating: 4.5,
    reviews: 1240,
    cover: 'https://picsum.photos/seed/midnight/400/600',
    category: 'Fiction',
    description: 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.',
    featured: true
  },
  {
    id: '2',
    title: 'Atomic Habits',
    author: 'James Clear',
    price: 1650,
    rating: 4.9,
    reviews: 5600,
    cover: 'https://picsum.photos/seed/habits/400/600',
    category: 'Non-Fiction',
    description: 'No matter your goals, Atomic Habits offers a proven framework for improving—every day. James Clear, one of the world’s leading experts on habit formation, reveals practical strategies.',
    featured: true
  },
  {
    id: '3',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    price: 999,
    rating: 4.2,
    reviews: 890,
    cover: 'https://picsum.photos/seed/gatsby/400/600',
    category: 'Classics',
    description: 'The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time the New York Times noted "gin was the national drink and sex the national obsession."',
    featured: false
  },
  {
    id: '4',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    price: 1999,
    rating: 4.8,
    reviews: 2100,
    cover: 'https://picsum.photos/seed/hailmary/400/600',
    category: 'Sci-Fi',
    description: 'Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish.',
    featured: true
  },
  {
    id: '5',
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    price: 1250,
    rating: 4.4,
    reviews: 3400,
    cover: 'https://picsum.photos/seed/silent/400/600',
    category: 'Mystery',
    description: 'Alicia Berenson’s life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London’s most desirable areas.',
    featured: false
  },
  {
    id: '6',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    price: 1800,
    rating: 4.7,
    reviews: 4500,
    cover: 'https://picsum.photos/seed/sapiens/400/600',
    category: 'History',
    description: 'Earth is 4.5 billion years old. In just a fraction of that time, one species among countless others has conquered it: us. Us humans.',
    featured: false
  },
  {
    id: '7',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    price: 799,
    rating: 4.6,
    reviews: 12000,
    cover: 'https://picsum.photos/seed/alchemist/400/600',
    category: 'Fiction',
    description: 'A fable about following your dream. Santiago, an Andalusian shepherd boy, travels from his homeland in Spain to the Egyptian desert in search of a treasure buried in the Pyramids.',
    featured: true
  },
  {
    id: '8',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    price: 1550,
    rating: 4.5,
    reviews: 3200,
    cover: 'https://picsum.photos/seed/thinking/400/600',
    category: 'Non-Fiction',
    description: 'Daniel Kahneman, the renowned psychologist and winner of the Nobel Prize in Economics, takes us on a groundbreaking tour of the mind.',
    featured: false
  },
  {
    id: '9',
    title: 'Dune',
    author: 'Frank Herbert',
    price: 2199,
    rating: 4.7,
    reviews: 8500,
    cover: 'https://picsum.photos/seed/dune/400/600',
    category: 'Sci-Fi',
    description: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world.',
    featured: true
  },
  {
    id: '10',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    price: 1100,
    rating: 4.8,
    reviews: 4200,
    cover: 'https://picsum.photos/seed/money/400/600',
    category: 'Non-Fiction',
    description: 'Doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people.',
    featured: false
  },
  {
    id: '11',
    title: 'The White Tiger',
    author: 'Aravind Adiga',
    price: 399,
    rating: 4.3,
    reviews: 1500,
    cover: 'https://picsum.photos/seed/whitetiger/400/600',
    category: 'Fiction',
    description: 'The White Tiger is the story of Balram Halwai’s journey from a poor village to the heights of success as an entrepreneur in Bangalore.',
    featured: false
  },
  {
    id: '12',
    title: 'The God of Small Things',
    author: 'Arundhati Roy',
    price: 450,
    rating: 4.5,
    reviews: 2800,
    cover: 'https://picsum.photos/seed/smallthings/400/600',
    category: 'Fiction',
    description: 'The story of twins Estha and Rahel, and the tragic events that shape their lives in the state of Kerala, India.',
    featured: true
  },
  {
    id: '13',
    title: 'The Palace of Illusions',
    author: 'Chitra Banerjee Divakaruni',
    price: 599,
    rating: 4.6,
    reviews: 3200,
    cover: 'https://picsum.photos/seed/palace/400/600',
    category: 'Fiction',
    description: 'A reimagining of the world-famous Indian epic, the Mahabharata—told from the point of view of Panchaali, also known as Draupadi.',
    featured: true
  },
  {
    id: '14',
    title: 'Train to Pakistan',
    author: 'Khushwant Singh',
    price: 299,
    rating: 4.4,
    reviews: 1200,
    cover: 'https://picsum.photos/seed/train/400/600',
    category: 'History',
    description: 'A classic novel about the partition of India in 1947, set in a small village on the border between India and Pakistan.',
    featured: false
  },
  {
    id: '15',
    title: 'Malgudi Days',
    author: 'R.K. Narayan',
    price: 350,
    rating: 4.7,
    reviews: 4500,
    cover: 'https://picsum.photos/seed/malgudi/400/600',
    category: 'Fiction',
    description: 'A collection of short stories set in the fictional town of Malgudi, capturing the essence of Indian life with humor and warmth.',
    featured: true
  },
  {
    id: '16',
    title: 'Shantaram',
    author: 'Gregory David Roberts',
    price: 899,
    rating: 4.5,
    reviews: 6700,
    cover: 'https://picsum.photos/seed/shantaram/400/600',
    category: 'Fiction',
    description: 'A powerful novel based on the author’s own life, following an escaped Australian convict who finds a new life in the slums of Bombay.',
    featured: false
  },
  {
    id: '17',
    title: 'The Immortals of Meluha',
    author: 'Amish Tripathi',
    price: 499,
    rating: 4.6,
    reviews: 8900,
    cover: 'https://picsum.photos/seed/meluha/400/600',
    category: 'Fiction',
    description: 'The first book of the Shiva Trilogy, reimagining the Hindu god Shiva as a mortal man who becomes a legend.',
    featured: true
  },
  {
    id: '18',
    title: 'Wings of Fire',
    author: 'A.P.J. Abdul Kalam',
    price: 325,
    rating: 4.9,
    reviews: 15000,
    cover: 'https://picsum.photos/seed/wings/400/600',
    category: 'Non-Fiction',
    description: 'The autobiography of Dr. A.P.J. Abdul Kalam, the former President of India and a renowned scientist, inspiring millions with his journey.',
    featured: true
  },
  {
    id: '19',
    title: 'The Guide',
    author: 'R.K. Narayan',
    price: 275,
    rating: 4.4,
    reviews: 2100,
    cover: 'https://picsum.photos/seed/guide/400/600',
    category: 'Fiction',
    description: 'The story of Raju, a corrupt tour guide who is mistaken for a holy man and eventually becomes one.',
    featured: false
  },
  {
    id: '20',
    title: 'Interpreter of Maladies',
    author: 'Jhumpa Lahiri',
    price: 425,
    rating: 4.6,
    reviews: 3800,
    cover: 'https://picsum.photos/seed/interpreter/400/600',
    category: 'Fiction',
    description: 'A collection of nine short stories that explore the lives of Indians and Indian Americans caught between two cultures.',
    featured: false
  },
  {
    id: '21',
    title: 'The Blue Umbrella',
    author: 'Ruskin Bond',
    price: 199,
    rating: 4.8,
    reviews: 5200,
    cover: 'https://picsum.photos/seed/umbrella/400/600',
    category: 'Fiction',
    description: 'A short and humorous novel about a young girl named Binya and her beautiful blue silk umbrella.',
    featured: false
  },
  {
    id: '22',
    title: 'The Namesake',
    author: 'Jhumpa Lahiri',
    price: 399,
    rating: 4.5,
    reviews: 4100,
    cover: 'https://picsum.photos/seed/namesake/400/600',
    category: 'Fiction',
    description: 'The story of the Ganguli family, moving from Calcutta to New York, and their son Gogol’s struggle with his identity.',
    featured: false
  },
  {
    id: '23',
    title: 'A Fine Balance',
    author: 'Rohinton Mistry',
    price: 599,
    rating: 4.7,
    reviews: 3200,
    cover: 'https://picsum.photos/seed/balance/400/600',
    category: 'Fiction',
    description: 'Set in India during the mid-1970s, it tells the story of four strangers whose lives come together in a cramped apartment.',
    featured: true
  },
  {
    id: '24',
    title: 'The Inheritance of Loss',
    author: 'Kiran Desai',
    price: 450,
    rating: 4.3,
    reviews: 1800,
    cover: 'https://picsum.photos/seed/loss/400/600',
    category: 'Fiction',
    description: 'A story about the effects of colonialism and the search for identity in a changing world.',
    featured: false
  },
  {
    id: '25',
    title: 'Midnight\'s Children',
    author: 'Salman Rushdie',
    price: 699,
    rating: 4.6,
    reviews: 5500,
    cover: 'https://picsum.photos/seed/midnightchildren/400/600',
    category: 'Fiction',
    description: 'A masterpiece of magical realism, following the lives of children born at the stroke of midnight on India’s independence.',
    featured: true
  },
  {
    id: '26',
    title: 'The Shadow Lines',
    author: 'Amitav Ghosh',
    price: 425,
    rating: 4.5,
    reviews: 2400,
    cover: 'https://picsum.photos/seed/shadow/400/600',
    category: 'Fiction',
    description: 'A novel that explores the boundaries between people and nations, and the power of memory.',
    featured: false
  },
  {
    id: '27',
    title: 'Do It Today',
    author: 'Darius Foroux',
    price: 350,
    rating: 4.4,
    reviews: 1200,
    cover: 'https://picsum.photos/seed/doit/400/600',
    category: 'Non-Fiction',
    description: 'Overcome procrastination, improve productivity, and achieve more by taking action today.',
    featured: false
  },
  {
    id: '28',
    title: 'The 5 AM Club',
    author: 'Robin Sharma',
    price: 499,
    rating: 4.7,
    reviews: 9800,
    cover: 'https://picsum.photos/seed/5am/400/600',
    category: 'Non-Fiction',
    description: 'Own your morning, elevate your life. A revolutionary morning routine that has helped millions achieve epic results.',
    featured: true
  },
  {
    id: '29',
    title: 'Ikigai',
    author: 'Hector Garcia',
    price: 550,
    rating: 4.8,
    reviews: 15000,
    cover: 'https://picsum.photos/seed/ikigai/400/600',
    category: 'Non-Fiction',
    description: 'The Japanese secret to a long and happy life, focusing on finding your purpose and living with joy.',
    featured: true
  },
  {
    id: '30',
    title: 'Man\'s Search for Meaning',
    author: 'Viktor Frankl',
    price: 399,
    rating: 4.9,
    reviews: 25000,
    cover: 'https://picsum.photos/seed/meaning/400/600',
    category: 'Non-Fiction',
    description: 'A psychiatrist’s memoir of his experiences in Nazi concentration camps and his development of logotherapy.',
    featured: true
  }
];

export const CATEGORIES = ['All', 'Fiction', 'Non-Fiction', 'Classics', 'Mystery', 'Sci-Fi', 'History'];
